WIP: feat: defendant solicitor acknowledges service (CMC-402)
hmcts/unspec-service pull request #102
Opened 2020-08-03 13:46 UTC by pd-dudkiewicz

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/CMC-402

### Change description ###

Added Acknowledges Service event for defendant solicitor.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2020-08-04 14:08 UTC, AlisonRevittHM requested changes
data review

2020-08-04 14:08 UTC, AlisonRevittHM commented on ccd-definition/CaseField.json
> +    "ID": "responseIntention",
Is this the respondent's solicitor's response? If so this should be respondent1ResponseIntention

2020-08-10 10:39 UTC, dharmendrak submitted a review, later dismissed

2020-08-12 08:53 UTC, dharmendrak approved these changes

2020-08-12 09:17 UTC, sabahirfan commented on src/main/java/uk/gov/hmcts/reform/unspec/handler/callback/AcknowledgeServiceCallbackHandler.java
> +                                 + "\n\n[Download the Acknowledgement of Service form](%s)",
`%n%n` isn't sonar complaining  about code smell here?

2020-08-12 09:29 UTC, sabahirfan approved these changes

2020-08-18 10:19 UTC, merged