fix: added min value validation to claim value
hmcts/unspec-service pull request #500
Opened 2021-01-08 16:51 UTC by pd-dudkiewicz

### JIRA link (if applicable) ###

### Change description ###

The service returned an error when claim value was set to 0£, as there's no fee available.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2021-01-11 09:11 UTC, swalker125 approved these changes

2021-01-11 10:35 UTC, swalker125 requested changes
could you update this to 100? Should solve the other bug https://tools.hmcts.net/jira/browse/CMC-1157

Validated with Darren that a £1 minmum is ok

2021-01-11 11:26 UTC, swalker125 approved these changes

2021-01-11 12:03 UTC, dharmendrak approved these changes

2021-01-11 12:09 UTC, sabahirfan approved these changes

2021-01-12 13:37 UTC, douglasrice approved these changes

2021-01-12 14:45 UTC, merged