refactor: Move Capture Defendant email to new screen
hmcts/unspec-service pull request #696
Opened 2021-03-23 15:30 UTC by devmarcy

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/CMC-1304

### Change description ###

* Created new screen and put email capture on it
* In doing so, email capture was removed from previous screen

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2021-03-23 16:52 UTC, dharmendrak submitted a review, later dismissed

2021-03-23 17:03 UTC, sabahirfan reviewed
Don't we need to update e2e test for this?

2021-03-24 09:06 UTC, swalker125 requested changes
Have you run api  / e2e tests locally?

2021-03-24 17:05 UTC, pd-dudkiewicz approved these changes

2021-03-26 10:34 UTC, swalker125 approved these changes

2021-03-30 13:14 UTC, merged