tech: edge case scenarios rpa contracts with minimal data (CMC-1429)
hmcts/unspec-service pull request #701
Opened 2021-03-24 13:16 UTC by sabahirfan

### JIRA link (if applicable) ###
[CMC-1429](url)

### Change description ###
This PR adds minimal data scenarios for RPA pact tests.

**Does this PR introduce a breaking change?** (check one with "x")

- [ ] Yes
- [x] No

2021-03-29 08:57 UTC, pd-dudkiewicz submitted a review, later dismissed

2021-04-09 09:36 UTC, dharmendrak submitted a review, later dismissed

2021-04-09 10:43 UTC, dharmendrak approved these changes

2021-04-09 12:29 UTC, pd-dudkiewicz requested changes
@sabahirfan can we please move that PR to new repo?

2021-04-13 13:56 UTC, pd-dudkiewicz commented
Moved to new repo https://github.com/hmcts/civil-damages-service/pull/48

2021-04-13 13:56 UTC, closed without merging