refactor: empty non working days file (CMC-1465)
hmcts/unspec-service pull request #756
Opened 2021-04-07 13:39 UTC by devmarcy

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CMC-1465

### Change description ###
* emptied `unspec-service/src/main/resources/data/non-working_days.dat`

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2021-04-07 15:22 UTC, dharmendrak approved these changes

2021-04-08 08:16 UTC, swalker125 requested changes
I think it makes more sense to do this on the new repo rather than here 

https://github.com/hmcts/civil-damages-service/blob/master/src/main/resources/data/non-working_days.dat

2021-04-12 14:14 UTC, douglasrice approved these changes

2021-04-14 08:07 UTC, pd-dudkiewicz commented
merged in https://github.com/hmcts/civil-damages-service/pull/36

2021-04-14 08:07 UTC, closed without merging