impr: added pagination to es queries (CMC-336)
hmcts/unspec-service pull request #76
Opened 2020-07-23 15:59 UTC by swalker125

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/CMC-336

### Change description ###

ES only returns 10 cases by default. Rather than add size param we will keep querying 10 results at a time.

This PR also adds state check to existing case stayed filter

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2020-07-23 22:04 UTC, ckalista requested changes
We probably will have to revisit the potential risk of endless loop. Other than that the other comment is more a suggestion for improvement to consider introducing some sort of generic pagination handling mechanism since we will need it again and again...can do it later when we encounter the need, up to you 👍

2020-07-23 22:04 UTC, ckalista commented on src/main/java/uk/gov/hmcts/reform/unspec/service/search/ElasticSearchService.java
> +        while (searchResult.getTotal() > caseDetails.size()) {
That's dangerous. If for whatever reason subsequent ES queries don't return any result (most likely won't happen but still...) we are at risk of looping endlessly which could cause a DOS on ES but also break our own service 💥 :)

Safer approach is a good old for loop, working out how many pages we have got 👍

2020-07-23 22:04 UTC, ckalista commented on src/main/java/uk/gov/hmcts/reform/unspec/service/search/CaseStayedSearchService.java
> +            of("query",
We could probably try to build a simple reusable mechanism to handle paging completely transparently. There is a full query DSL for ES that could be used to build the basic query that can then be augmented using composition. eg I could imagine something like this: `fetchAll(dslQuery)`

https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/java-query-dsl.html

2020-07-23 22:04 UTC, ckalista commented on src/main/java/uk/gov/hmcts/reform/unspec/service/search/CaseStayedSearchService.java
> +            of("query",
Actually in CMC we used that DSL: https://github.com/hmcts/cmc-claim-store/blob/d76f3e9bb3f0228dcde1cf871b17a9cece7e61f4/src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/CCDElasticSearchRepository.java#L44

2020-07-24 08:09 UTC, swalker125 commented on src/main/java/uk/gov/hmcts/reform/unspec/service/search/ElasticSearchService.java
> +        while (searchResult.getTotal() > caseDetails.size()) {
haha I was up late thinking exactly this last night 😅

2020-07-24 08:10 UTC, swalker125 commented on src/main/java/uk/gov/hmcts/reform/unspec/service/search/CaseStayedSearchService.java
> +            of("query",
I can't stand this horrible map of of of of of so yes, wasn't aware of this. Shall implement

2020-07-24 12:28 UTC, douglasrice approved these changes

2020-07-24 13:06 UTC, dharmendrak submitted a review, later dismissed

2020-07-24 13:46 UTC, douglasrice submitted a review, later dismissed

2020-07-24 13:46 UTC, ckalista requested changes

2020-07-24 13:46 UTC, ckalista commented on src/main/java/uk/gov/hmcts/reform/unspec/service/search/ElasticSearchService.java
> +        for (int i = esDefaultSearchLimit; caseDetails.size() < searchResult.getTotal(); i = i + esDefaultSearchLimit) {
Still potentially have a risk here in case ES query doesn't return any record subsequently. Discussing this on slack... 👍

2020-07-24 14:49 UTC, ckalista approved these changes

2020-07-31 11:30 UTC, douglasrice approved these changes

2020-07-31 11:44 UTC, merged